import Store from "@/db/Store";
import { useTheme } from "@/components/ThemeContext";
import { Transaction } from "@/types";
import colors from "@/utils/helper/colors";
import { ChevronLeft, ChevronRight } from "lucide-react-native";
import React, { useEffect, useMemo, useState } from "react";
import { ScrollView, Share, Text, TouchableOpacity, View } from "react-native";
import * as Animatable from "react-native-animatable";

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const WEEKDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export default function Wrapped() {
  const { colors: t, isDark, cardStyle } = useTheme();
  const [history, setHistory] = useState<Transaction[]>([]);
  const [year, setYear] = useState(new Date().getFullYear());

  useEffect(() => {
    const load = async () => {
      const data = await Store.getData();
      setHistory(data.user.history || []);
    };
    load();
  }, []);

  const yearTxns = useMemo(() =>
    history.filter((txn) => new Date(txn.date).getFullYear() === year),
  [history, year]);

  const outgoing = yearTxns.filter((t) => t.type === "outgoing");
  const incoming = yearTxns.filter((t) => t.type === "incoming");

  const totalSpent = outgoing.reduce((s, t) => s + t.amount, 0);
  const totalEarned = incoming.reduce((s, t) => s + t.amount, 0);
  const totalTxns = yearTxns.length;

  // Top category
  const catMap: Record<string, number> = {};
  outgoing.forEach((t) => { catMap[t.category || "others"] = (catMap[t.category || "others"] || 0) + t.amount; });
  const topCat = Object.entries(catMap).sort((a, b) => b[1] - a[1])[0];

  // Monthly spending
  const monthlySpend = useMemo(() => {
    const arr = new Array(12).fill(0);
    outgoing.forEach((t) => { arr[new Date(t.date).getMonth()] += t.amount; });
    return arr;
  }, [outgoing]);
  const maxMonth = Math.max(...monthlySpend, 1);
  const biggestMonthIdx = monthlySpend.indexOf(Math.max(...monthlySpend));

  // Biggest single expense
  const biggestTxn = outgoing.length > 0
    ? outgoing.reduce((max, t) => t.amount > max.amount ? t : max, outgoing[0])
    : null;

  // Most active weekday
  const dayCount = new Array(7).fill(0);
  yearTxns.forEach((t) => { dayCount[new Date(t.date).getDay()]++; });
  const busiestDay = WEEKDAYS[dayCount.indexOf(Math.max(...dayCount))];

  // Average per day
  const daysInYear = year === new Date().getFullYear()
    ? Math.ceil((Date.now() - new Date(year, 0, 1).getTime()) / 86400000) || 1
    : 365;
  const dailyAvg = totalSpent / daysInYear;

  const shareWrapped = async () => {
    const msg = `🎉 ${year} Spending Wrapped

💸 Total Spent: ₹${totalSpent.toFixed(0)}
💰 Total Earned: ₹${totalEarned.toFixed(0)}
📝 ${totalTxns} transactions

🏆 Top Category: ${topCat ? topCat[0] : "—"} (₹${topCat ? topCat[1].toFixed(0) : 0})
📅 Biggest Month: ${MONTHS[biggestMonthIdx]} (₹${monthlySpend[biggestMonthIdx].toFixed(0)})
💥 Biggest Expense: ${biggestTxn ? `₹${biggestTxn.amount.toFixed(0)} — ${biggestTxn.description}` : "—"}
📊 Daily Average: ₹${dailyAvg.toFixed(0)}
🗓️ Most Active Day: ${busiestDay}

— Generated by Resolve`;
    await Share.share({ message: msg });
  };

  const barColors = [colors.chartGreen, colors.chartBlue, colors.chartOrange, colors.chartPurple, colors.chartRed];

  if (yearTxns.length === 0) {
    return (
      <View style={{ backgroundColor: t.bg }} className="flex-1 items-center justify-center px-6">
        <Text className="text-5xl mb-4">📦</Text>
        <Text style={{ color: t.text }} className="text-xl font-bold mb-2">No data for {year}</Text>
        <Text style={{ color: t.textMuted }} className="text-sm text-center">Start adding transactions to see your yearly wrapped!</Text>
        <View className="flex-row gap-4 mt-6">
          <TouchableOpacity onPress={() => setYear(year - 1)} className="px-4 py-2 rounded-xl bg-neutral-800">
            <Text className="text-white">{year - 1}</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  return (
    <ScrollView style={{ backgroundColor: t.bg }} className="flex-1 px-6 pt-4">
      {/* Year selector */}
      <View className="flex-row items-center justify-between mb-2">
        <TouchableOpacity onPress={() => setYear(year - 1)} className="p-2">
          <ChevronLeft size={24} color={t.text} />
        </TouchableOpacity>
        <Text style={{ color: t.text }} className="text-2xl font-bold">{year} Wrapped</Text>
        <TouchableOpacity onPress={() => setYear(year + 1)} className="p-2">
          <ChevronRight size={24} color={t.text} />
        </TouchableOpacity>
      </View>
      <Text style={{ color: t.textMuted }} className="text-sm text-center mb-6">Your year in spending</Text>

      {/* Hero stats */}
      <Animatable.View animation="fadeInUp" duration={600}>
        <View style={cardStyle} className="rounded-2xl p-6 mb-4 items-center">
          <Text className="text-5xl mb-3">💸</Text>
          <Text style={{ color: t.textSecondary }} className="text-sm">You spent a total of</Text>
          <Text className="text-red-400 text-4xl font-bold mt-1">₹{totalSpent.toFixed(0)}</Text>
          <Text style={{ color: t.textMuted }} className="text-xs mt-2">across {totalTxns} transactions</Text>
        </View>
      </Animatable.View>

      <Animatable.View animation="fadeInUp" delay={100} duration={600}>
        <View style={cardStyle} className="rounded-2xl p-6 mb-4 items-center">
          <Text className="text-5xl mb-3">💰</Text>
          <Text style={{ color: t.textSecondary }} className="text-sm">You earned</Text>
          <Text className="text-green-400 text-4xl font-bold mt-1">₹{totalEarned.toFixed(0)}</Text>
        </View>
      </Animatable.View>

      {/* Fun stats grid */}
      <Animatable.View animation="fadeInUp" delay={200} duration={600}>
        <View className="flex-row gap-3 mb-4">
          <View style={cardStyle} className="flex-1 rounded-2xl p-4 items-center">
            <Text className="text-2xl mb-1">🏆</Text>
            <Text style={{ color: t.textMuted }} className="text-xs">Top Category</Text>
            <Text style={{ color: t.text }} className="font-bold mt-1">{topCat ? topCat[0] : "—"}</Text>
            {topCat && <Text className="text-red-400 text-xs mt-1">₹{topCat[1].toFixed(0)}</Text>}
          </View>
          <View style={cardStyle} className="flex-1 rounded-2xl p-4 items-center">
            <Text className="text-2xl mb-1">📊</Text>
            <Text style={{ color: t.textMuted }} className="text-xs">Daily Avg</Text>
            <Text style={{ color: t.text }} className="font-bold mt-1">₹{dailyAvg.toFixed(0)}</Text>
          </View>
          <View style={cardStyle} className="flex-1 rounded-2xl p-4 items-center">
            <Text className="text-2xl mb-1">🗓️</Text>
            <Text style={{ color: t.textMuted }} className="text-xs">Busiest Day</Text>
            <Text style={{ color: t.text }} className="font-bold mt-1">{busiestDay}</Text>
          </View>
        </View>
      </Animatable.View>

      {/* Biggest expense */}
      {biggestTxn && (
        <Animatable.View animation="fadeInUp" delay={300} duration={600}>
          <View style={cardStyle} className="rounded-2xl p-5 mb-4">
            <Text className="text-2xl mb-2">💥</Text>
            <Text style={{ color: t.textSecondary }} className="text-sm">Biggest Single Expense</Text>
            <Text className="text-red-400 text-2xl font-bold mt-1">₹{biggestTxn.amount.toFixed(0)}</Text>
            <Text style={{ color: t.textMuted }} className="text-xs mt-1">
              {biggestTxn.description} · {new Date(biggestTxn.date).toLocaleDateString()}
            </Text>
          </View>
        </Animatable.View>
      )}

      {/* Monthly bar chart */}
      <Animatable.View animation="fadeInUp" delay={400} duration={600}>
        <Text style={{ color: t.text }} className="text-lg font-semibold mb-3">Monthly Breakdown</Text>
        <View style={cardStyle} className="rounded-2xl p-5 mb-4">
          <View className="flex-row items-end gap-1" style={{ height: 120 }}>
            {monthlySpend.map((val, i) => {
              const h = maxMonth > 0 ? (val / maxMonth) * 100 : 0;
              const isBiggest = i === biggestMonthIdx && val > 0;
              return (
                <View key={i} className="flex-1 items-center">
                  <View
                    style={{
                      height: `${Math.max(h, 3)}%`,
                      backgroundColor: isBiggest ? "#EF4444" : barColors[i % barColors.length],
                      borderRadius: 4,
                      width: "80%",
                    }}
                  />
                  <Text style={{ color: t.textMuted }} className="text-[9px] mt-1">{MONTHS[i]}</Text>
                </View>
              );
            })}
          </View>
        </View>
      </Animatable.View>

      {/* Category breakdown */}
      {Object.keys(catMap).length > 0 && (
        <Animatable.View animation="fadeInUp" delay={500} duration={600}>
          <Text style={{ color: t.text }} className="text-lg font-semibold mb-3">Category Split</Text>
          <View style={cardStyle} className="rounded-2xl p-5 mb-4">
            {Object.entries(catMap).sort((a, b) => b[1] - a[1]).map(([cat, amt], i) => (
              <View key={cat} className="mb-3">
                <View className="flex-row justify-between mb-1">
                  <Text style={{ color: t.textSecondary }} className="text-sm">{cat}</Text>
                  <Text style={{ color: t.text }} className="text-sm font-semibold">₹{amt.toFixed(0)}</Text>
                </View>
                <View className="h-2 bg-neutral-800 rounded-full overflow-hidden">
                  <View
                    style={{ width: `${(amt / totalSpent) * 100}%`, backgroundColor: barColors[i % barColors.length] }}
                    className="h-full rounded-full"
                  />
                </View>
              </View>
            ))}
          </View>
        </Animatable.View>
      )}

      {/* Share button */}
      <TouchableOpacity onPress={shareWrapped} activeOpacity={0.85} className="bg-white py-4 rounded-2xl items-center mb-4">
        <Text className="text-black text-lg font-semibold">Share My Wrapped</Text>
      </TouchableOpacity>

      <View className="h-20" />
    </ScrollView>
  );
}
